# [START functions_ci_cd_cloud_build]
steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'function/dir/from/repo/root'
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: 'function/dir/from/repo/root'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'C0nsultWishlists', '--trigger-http', '--runtime', 'nodejs10', '--entry-point', 'consultWishlists']
  dir: 'function/dir/from/repo/root'
  - name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'WishlistDet4il', '--trigger-http', '--runtime', 'nodejs10', '--entry-point', 'wishlistDetail']
  dir: 'function/dir/from/repo/root'
# [END functions_ci_cd_cloud_build]
